### ISSUE TITLE
Table of contents is broken

### ISSUE THREAD

**Issue by acka47** [reconciliation-api/specs#10]
Locally, it looks just fine but not at https://reconciliation-api.github.io/specs/

**Comment by wetneb** [comment]
Yes I am puzzled by that too… It is very weird.

**Comment by wetneb** [comment]
I tried to investigate this but I still cannot figure out what is going wrong, so I have opened an issue here:
https://github.com/w3c/respec/issues/2524

**Comment by acka47** [comment]
Obviously, I overlooked to update one reference:


As I understand it, this is somehow causing the problem. Will update the reference in master.

**Comment by acka47** [comment]
It's fixed now after correcting the reference.Closing.
