### ISSUE TITLE
Redirect to the final version of the 0.1 specs

### ISSUE THREAD

**Issue by wetneb** [reconciliation-api/specs#122]
Since I have taken the steps to publish the 0.1 specs on the W3C website, we have a couple of problems at https://reconciliation-api.github.io/specs/0.1/:
* The link at "This version" points to a non-existing page because the date is automatically picked as today's date. The correct link is the "Last published version" underneath
* The page takes quite some time to load with Respec trying to fetch references dynamically (and failing, somehow?)

Therefore I would propose to remove this page and replace it by a redirect to https://www.w3.org/community/reports/reconciliation/CG-FINAL-specs-0.1-20230321/.
We could move `0.1/index.html` to something like `0.1/source.html` to keep the source of the published spec around (in case we want to make minor corrections later, which I think we should still be able to publish at the same URL on `w3.org`).

**Comment by fsteeg** [comment]
> I would propose to remove this page and replace it by a redirect to https://www.w3.org/community/reports/reconciliation/CG-FINAL-specs-0.1-20230321/.
We could move 0.1/index.html to something like 0.1/source.html to keep the source

Sounds good!

**Comment by thadguidry** [comment]
Agree sounds good.  Yes, as long as folks don't lose access to view the 0.1 spec _somewhere_  when they ask to see it or open an issue about it.
