### ISSUE TITLE
Schema mixes snake and camel case?

### ISSUE THREAD

**Issue by derenrich** [reconciliation-api/specs#150]
Why does the API mix camel and snake case? The [service manifest ](https://www.w3.org/community/reports/reconciliation/CG-FINAL-specs-0.2-20230410/#service-manifest )has keys named 

- `identifierSpace`, `schemaSpace`, `defaultTypes`
- `feature_view`

Presumably you would want to use one or the other? Is it that you are using snake for objects and camel for values/arrays? But later in [suggest metadata](https://www.w3.org/community/reports/reconciliation/CG-FINAL-specs-0.2-20230410/#suggest-metadata) you use `service_url` to refer to a string? I'm confused.

**Comment by derenrich** [comment]
Also, the manifest spec mentions a key called `batchSize` but this is not included in the json schema at the bottom of the spec

**Comment by wetneb** [comment]
Thanks! I think it would be worth normalizing this in the current draft indeed.
