### ISSUE TITLE
Should the data type for `limit` parameter be a String or Number?

### ISSUE THREAD

**Issue by thadguidry** [reconciliation-api/specs#167]
The current wording for `limit` under Data Extension Property Proposals says
> Optionally, the requested limit

and ideally would instead give the data type

> An optional string value to control the number of proposed properties fetched.

We do have a paragraph further above that `limit` parameter that mentions it's a String data type? as 

> The service SHOULD support an optional limit query string parameter to control the number of proposed properties.

But I noticed that we have other numerical values for things like this, such as Query's `limit`, and Preview's `width`, `height` and also Candidates `score`, and wondered if we should ensure that we use numerical data types for parameter values always expected to be a number like `limit` ?

**Comment by wetneb** [comment]
The example makes it clear that this limit should be an integer, not a string. Would you like to make a PR to clarify this in the description of the field if you think that would be helpful?

**Comment by thadguidry** [comment]
We absolutely don't want to wrap a standard around examples.  W3C fully says "do not do that".

Yeap, PR coming.

**Comment by thadguidry** [comment]
Generally, we need better display of data types for parameters in Respec which can sorta help #95 and also #157

So, I'll work on all that in separate PR's
