### ISSUE TITLE
ReSpec error in current draft

### ISSUE THREAD

**Issue by fsteeg** [reconciliation-api/specs#168]
Opening the current draft at https://reconciliation-api.github.io/specs/draft/ I get (after some time):

> Document is not associated with a [W3C group](https://respec.org/w3c/groups/). Defaulting to 'base' status.
>
> How to fix: Use the [group](https://respec.org/docs/#group) configuration option to associated this document with a W3C group.

The links don't seem to resolve.

**Comment by wetneb** [comment]
I've also witnessed this myself some time ago, but cannot reproduce it anymore. I'd bet this was a temporary hosting hiccup somewhere. Should we close?

**Comment by fsteeg** [comment]
Yes, no longer happening here too, closing.
