### ISSUE TITLE
Clarify expected behaviour on invalid input

### ISSUE THREAD

**Issue by wetneb** [reconciliation-api/specs#171]
We don't say much about what should happen when invalid input is supplied to our endpoints.
For instance:
* supplying an invalid property or type identifier in a reconciliation query 
* previewing an entity with an invalid identifier
* submitting a data extension query with invalid property settings

We should at least mention the expected HTTP code and format of the response body.

**Comment by fsteeg** [comment]
Seems to be a duplicate of https://github.com/reconciliation-api/specs/issues/83, closing.
