### ISSUE TITLE
Authentication support

### ISSUE THREAD

**Issue by wetneb** [reconciliation-api/specs#26]
We would like to make it possible for reconciliation services to support authentication by letting clients pass an API key.

For instance, clients could send an API key along with their queries to the service, via a new parameter (such as `api_key`).

Services would be able to announce in their manifest that they support or require API keys, with perhaps extra metadata to make it easier to prompt the user for such keys.

Mailing list thread: https://lists.w3.org/Archives/Public/public-reconciliation/2019Jul/0010.html
OpenRefine issue: https://github.com/OpenRefine/OpenRefine/issues/2015

**Comment by wetneb** [comment]
I think there seems to be a good consensus around this feature (see thread) so I propose we ship it in the upcoming version.

**Comment by workergnome** [comment]
Definitely a useful thing to do.  What would the manifest look like? And does using a token like this also mean that we'd want to require HTTPS?

**Comment by wetneb** [comment]
No strong feelings about the manifest! If you have any suggestion… :)

**Comment by tfmorris** [comment]
One thing that a manifest-based approach doesn't support (at least directly) is authenticated access to the manifest in the first place. Are there cases where it's desirable to not have the manifest publically accessible?

**Comment by wetneb** [comment]
Good point! Personally I cannot think of a case where that would be a problem.
What are the alternatives? If the service uses HTTP 401 responses to ask for credentials, this would just follow the HTTP standard but would only be applicable to HTTP auth. If the service redirects to point the user to a login page, I think it is going to be tricky to integrate in tools like OpenRefine, no?
