### ISSUE TITLE
Give users more control over candidate scoring

### ISSUE THREAD

**Issue by wetneb** [reconciliation-api/specs#31]
As an API user, the scores returned by reconciliation services are generally opaque: I have no idea what scoring method a service uses without diving deep in its source code. I do not know what a certain score means and it is hard to decide on a threshold above which I can trust matches because of that.

There are basically two classes of approaches to solve this problem.

The first one would be to add more query parameters, to let the user say "it is very important that this particular property matches well" or "the type constraint is only indicative" or similar things (#24). By doing this we give more control to the user over the scoring function. The problems I see with this approach are as follows:
* These new configuration options will still be a bit hard to define for the service and to understand for the user: how to measure the importance of a feature if you don't really know what the scoring function is?
* If I reconcile a column with some settings and then figure out that I want to increase the importance of a particular feature, I will have to re-run the entire reconciliation process since the scoring method is still server-side. This costs time and resources. Therefore this workflow does not tie in very well with machine learning approaches to record linkage.

The second one would be to expose more features in reconciliation responses. The reconciliation service could return not just a single score, but also the list of features it used to compute this global score. Something like this:
```json
{
    "result": [
        {
            "id": "Q2345",
            "name": "My item",
            "type": [ ... ],
            "score": 57.89,
            "features": {
                 "name_levenshtein": 89.63,
                 "name_tfidf": 47.82,
                 "type_match_Q5": 12.3,
                 "type_match_Q47": 50.0,
                 "p_P3477_match": 38.0,
                 "pagerank": 374.89,
                 "nb_statements": 56,
            }
        },
        ...
     ]
}
```
As a client, this would make it possible to come up with your own scoring method based on the features returned by the service, and possibly other ones computed locally. Many of these features require global statistics about the entire database (the PageRank of an entity in a graph, the TF-IDF scores of a sequence of words in a given field), so it makes sense to let the service compute them.

The main difficulty with this approach is coming up with *simple* user interfaces to help users create their own scoring functions without having to know too much about machine learning. This could be done by implementing some active learning strategy where the user only has to manually a few reconciliation candidates (strategically picked by the software), to learn a simple candidate classifier on the basis of these features.
On the plus side, this would make the reconciliation API more relevant to existing software projects which implement feature-based record linkage: [recordlinkage (python package)](https://recordlinkage.readthedocs.io/en/latest/), [reclink (R package)](http://fmwww.bc.edu/RePEc/bocode/r/reclink.html), and many others.

**Comment by VladimirAlexiev** [comment]
This is a relevant topic. Eg see https://www.wikidata.org/wiki/Topic:Ve6hi3cgutbemtvh: Mix-n-Match uses a quick & dirty algorithm for "automatch" whereas the WD ranking methods give much better matches. MnM has a more expensive "automatch by search" method and Magnus is still working to make this more easily usable and/or the default method.
