### ISSUE TITLE
Add Description in Reconciliation Response

### ISSUE THREAD

**Issue by MatthiasWinkelmann** [reconciliation-api/specs#47]
(This is a suggestion, based on my use of OpenRefine with Wikidata. I am not sure how well it generalises, nor am I aware of all your previous considerations. So feel free to just close this if I'm not making sense)

I am currently slowed down far more than necessary in my workflow by the inability to distinguish different suggestions returned by the Wikidata reconciliation service. This is especially prominent with location names, which seem to be less unique than personal names. Wikidata also has issues with duplicates, and specifically the common duplication (/triplication) of a location's name between the name of the place, its administration, and often the next-higher administrative level.
 
As it is, this requires either manually triggering a hover effect for each suggestion, or to implement a complex workflow of generating columns for all suggestions and then adding columns for each with the description fetched from the service. 

Wikidata (rightly) keeps disambiguation information out of labels and records it in the description. This requires the description to be passed along, and to be shown, wherever a user is asked to chose between alternatives. Not doing so is already [putting pressure on Wikidata to compromise its labels. ](https://www.wikidata.org/wiki/Wikidata:Project_chat/Archive/2020/07#Klammerzusatz_hinter_Vornamen_und_Familiennamen)

Therefore, I'd like to suggest adding the description as an optional field for the reconciliation batch response. This also brings it closer to the suggestion response, possibly making life easier for systems providing both.

**Comment by jetztgradnet** [comment]
In our implementation of the Reconciliation API (which for now is mostly used between our own pieces of software) we also expanded the result a bit to also deliver a description along with id, label, type(s) and score. 
For some implementations it might make sense to allow sending additional values (not just description) also for performance reasons, i.e. something like adding results from the _Data Extension Service_ in the same response to avoid another round trip. Depending on how data is fetched from the endpoint, this set of properties is accessed/available already so it would be good if it can already be delivered at the same time. This would require being able to (optionally) specify additional properties to be retrieved in the query, though.

**Comment by wetneb** [comment]
I think it would be very useful to have descriptions returned alongside reconciliation candidates, and it would be pretty straightforward to include that in OpenRefine's UI. Returning specified properties would also make a lot of sense (I would have to think a bit more about the integration in OpenRefine, but as far as the specifications are concerned it should be pretty simple).

**Comment by tfmorris** [comment]
> Wikidata also has issues with duplicates, and specifically the common duplication (/triplication) of a location's name between the name of the place, its administration, and often the next-higher administrative level.

Although these have the same name, they're not actually duplicates. For this case, the type(s) provide(s) one level of disambiguation and the flyout/preview pane would typically include property values like the higher administrative level which provides a second level of disambiguation.

> Returning specified properties would also make a lot of sense 

If this is done, it would make more sense, I think, to have description be one of those requestable properties, rather than a separate standalone thing. A simple convention such as using properties with null for a specified value to mean that they are to be returned rather than used for matching would be an easy extension.

**Comment by wetneb** [comment]
> Although these have the same name, they're not actually duplicates.

I suspect @MatthiasWinkelmann refers to the true duplicates that Wikidata has for locations (mostly due to the careless import of Cebuano Wikipedia articles).

**Comment by gitonthescene** [comment]
@MatthiasWinkelmann FWIW, as a workaround you could try [splitting out the candidates](https://github.com/OpenRefine/OpenRefine/wiki/Recipes#13-reconciliation) and then _Edit Column_ -> _Add column from reconciled values_ using `SPARQL: Den` to pull the Wikidata descriptions.

**Comment by gitonthescene** [comment]
@jetztgradnet - Currently the spec [says](https://reconciliation-api.github.io/specs/latest/#dfn-matching-feature) that feature value should be either boolean or numeric but I don’t see the need for a restriction.  If they were strings they would seem to fit your purpose.  Currently OpenRefine [ignores](https://github.com/OpenRefine/OpenRefine/issues/3139#issuecomment-829653920) this part of the response so I’d assume there’s room to change the spec.
