### ISSUE TITLE
reconciliation-response schema is broken

### ISSUE THREAD

**Issue by acka47** [reconciliation-api/specs#5]
For example with a response `reconciliation-response.json` like 

```json
{
   "q1":{
      "result":"bla"
   }
}
```

this is also validated as correct:

`$ ajv -s schemas/reconciliation-response.json -d reconciliation-response.json 
reconciliation-response.json valid`

**Comment by wetneb** [comment]
That is because it was not meant to be used for the full response, only the list of candidates for a single query, as I tried to document in its description :)

**Comment by wetneb** [comment]
That is because it was not meant to be used for the full response, only the list of candidates for a single query, as I tried to document in its description :)

**Comment by acka47** [comment]
Sorry, then my other commits also don't make sense. Next time I will read the description first. ;-) However, wouldn't it make sense to have a schema for the full response. I think, we just have to take into accout the arbitrary keys (in the example `q1`) which should be easily done with `patternProperties`, see https://stackoverflow.com/questions/16222633/how-would-you-design-json-schema-for-an-arbitrary-key.

**Comment by wetneb** [comment]
yes, see my comments on the PR

**Comment by acka47** [comment]
You write at :

> I thought it could be useful to isolate the schema for a single response since it could then be used for both individual and multiple query modes (via $ref). But if we decide not to document the individual query mode at all, it would make sense to make it in one single big schema too.

As the single query mode is marked as deprecated in the documentation, I would go on and adjust the schema to validate the whole response. Then it would also fit with the text in the draft spec, see e.g. https://reconciliation-api.github.io/specs/#reconciliation-response-schema Ok?

**Comment by wetneb** [comment]
I think it is consistent with the text at the moment, since reconciliation response is defined as "a set of reconciliation candidates".

But sure, happy with that plan. (So the text would need to be updated)

**Comment by acka47** [comment]
Ok, will do that. (I meant the bit in the spec: "The reconciliation response schema can be used to validate the JSON serialization of any reconciliation response.")

**Comment by wetneb** [comment]
Yes, if you click on "reconciliation response" you get to the definition ;)

**Comment by acka47** [comment]
> Also, for consistency, if we have a single schema for multiple responses, then it would probably also make sense to have a single schema for multiple queries.

Yes, I made a PR for this with #9.
