### ISSUE TITLE
define `type_strict`

### ISSUE THREAD

**Issue by VladimirAlexiev** [reconciliation-api/specs#60]
Currently the spec says:
- `type_strict`: Optionally, a type strictness parameter, which can be one of the strings "should", "all" or "any".
- (later)
- NOTE: The meaning of the `type_strict` is unclear, it is inherited from Freebase's API but is not used or documented in OpenRefine.

This is a useful historical note, but a spec must fix the meaning of every option (or remove it). I propose to change it as follows (and put all text together):

- `type_strict`: Optionally, a type strictness parameter, which can have one of these string values:
  - missing or "should": types are used for candidate scoring together with other features (`query` and `properties`), but a type match is not required for a candidate to be returned
  - "all": all types must match for a candidate to be returned
  - "any": at least one type must match for a candidate to be returned
- NOTE: this parameter is not used or documented in OpenRefine, but can be used in other clients.

Related to #24: similar options are applicable to `properties`

**Comment by wetneb** [comment]
Closed by #115
