### ISSUE TITLE
Migrate CI out of Travis

### ISSUE THREAD

**Issue by wetneb** [reconciliation-api/specs#62]
Travis is discontinuing its free tier for open source projects.
We could use GitHub Actions instead.

**Comment by dr0i** [comment]
Don't want to hamper you to try other things, but as I understand it it's just that the domain `travis-ci.org` is shut down and you could migrate to `travis-ci.com`. The latter seems also to be free https://travis-ci.com/plans and at https://travis-ci.com it's said:

> Testing your open source
projects is always 100% free!
Seriously. Always. We like to think of it as our way of giving
back to a community that gives us so much as well.

(See also https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com.)

**Comment by wetneb** [comment]
Sadly their communication is very misleading - even for open source projects they have introduced some quotas and we are likely to run out of them at some point.

The stackoverflow post is quite old. See this: https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

**Comment by dr0i** [comment]
Oh, thx for the link! Didn't know this. Nice blog post. This preserves me to migrate to travis-ci.com and ending up unhappy. Also updated the "stack" entry.
