### ISSUE TITLE
From any REST API to the Reco API

### ISSUE THREAD

**Issue by yannnic** [reconciliation-api/specs#63]
Hi, 
it might not be the right place to ask this question. If so, i apologize and will be grateful if you tell me where is the good place.

I am looking for some maintained code that translates/wraps any REST API into a Refine reconciliation API. Do you know of such a thing ?
Our use case : at ABES (www.abes.fr), we developed a program to reconcile the mention of an author in a bibliographic record to an authory record (first in ours : www.idref.fr). It can be used as a web service and it would be even better if people could use it from Refine as if it were a Refine reco API. Rather than hard coding and providing another version of our service, we prefer to find a way to dynamically translate/wrap it.
Here is a [paper](https://hal.archives-ouvertes.fr/hal-02563630/document) about our program (Qualinka) and the curation interface that integrates it (www.paprika.idref.fr).
Thanks for your help :)
Yann

**Comment by wetneb** [comment]
Hi @yannnic,

This is a great idea! Yes there are plenty of reconciliation services which are implemented as wrappers on top of existing APIs.
You can find a list of publicly available endpoints at https://reconciliation-api.github.io/testbench/, and many of these endpoints are linked to their source code (in the first column).

Here are a few examples of endpoints implemented on top of existing APIs:
* In Python: the Wikidata endpoint is implemented as a wrapper on top of the Wikibase API: https://github.com/wetneb/openrefine-wikibase.
* In Java: [Conciliator](https://github.com/codeforkjeff/conciliator) offers multiple reconciliation endpoints, all implemented on top of public APIs (VIAF, ORCID, OpenLibrary)
* In PHP: some lightweight reconciliation services are hosted as PHP scripts, which wrap other public APIs (see the files starting with `reconciliation_` in https://github.com/rdmpage/phyloinformatics/tree/master/services, but beware that these have not been updated for a while).

**Comment by yannnic** [comment]
Hi Antonin,
Thanks you so much for your very useful answer.
I will have a look to these implementations.
Best
Yann

Le mer. 3 févr. 2021 à 17:31, Antonin Delpeuch <notifications@github.com> a
écrit :
