### ISSUE TITLE
When to supply the service manifest?

### ISSUE THREAD

**Issue by gitonthescene** [reconciliation-api/specs#64]
From [this example](https://github.com/mikejs/reconcile-demo/blob/master/reconcile.py) I understand that all interaction comes from a single endpoint and that the service manifest is to be delivered from the end point if it's not a query.  I think it might be worth making that explicit in the API.  If this is reason for leaving this ambiguous, then I think an explanation of why would be helpful.  Should the service manifest always be accessible with a GET request?

**Comment by wetneb** [comment]
@gitonthescene let me know if #64 helps.

**Comment by gitonthescene** [comment]
Much clearer to me.  Thanks very much.  FWIW, I thought I didn’t need CORS for a local service and it looks like I don’t.  I’m not sure what made me think I needed JSON-P.  Also my local service isn’t receiving the `Origin` header from OpenRefine.  That’s not a problem but it makes it tougher to calculate the `Access-Control-Allow-Origin` header.

Lastly, I’m building a more configurable `csv-reconcile` in Python using Flask.  You can set the CSV separator, quoting style, encoding, etc.  The clojure code in the census hasn’t been touched for two years and I don’t know clojure so I took this up.  It uses a Dice coefficient for scoring just as the old version does.

Thanks again

**Comment by wetneb** [comment]
Great, looking forward to seeing your version of `csv-reconcile`, it's a very popular software so it does deserve to be improved and maintained.
