### ISSUE TITLE
Versioning policy

### ISSUE THREAD

**Issue by wetneb** [reconciliation-api/specs#7]
We should decide on a way to maintain specs for different versions of the protocol, so people can unambiguously refer to a particular version.

We might still want to be able to edit the specifications of an older version (to improve the presentation, for instance), so I don't think git tags and GitHub releases are appropriate for that.

One possible solution would be to create sub-directories for each version. The files referenced by the specs (such as the schemas) would also need to be duplicated in these sub-directories.

**Comment by wetneb** [comment]
Beyond the constraint to be able to modify previous versions for editorial changes, we also want to host all versions simultaneously. That would work if we create one-subdirectory per version, but it would be nicer if GitHub pages supported URL schemes which let the branch vary (just like RTD hosts multiple versions of the documentation, using branches and tags).

**Comment by wetneb** [comment]
@acka47 @fsteeg, how do you feel about this issue?

I don't see a better solution than duplicating all files (including the schemas and examples) in subdirectories for each version… It's not great, but I'm not sure what else can be done. I am thinking of the following directory structure:

```
1.0/
1.1/
...
draft/
```

The `draft/` folder would be where we insert new features and introduce changes in the API in general. When we are happy with these changes, we release a new version of the specs by copying the draft folder to the next version number (adapting references to paths in the specs and JSON schemas). A script could potentially help with that.

When we make an editorial change, such as improving the description of a parameter, we probably want to do it in all relevant versions, not just in the `draft` folder. Not sure if tools can help with that.

**Comment by fsteeg** [comment]
I've discussed this with @acka47 and that approach sounds good to us.

If it makes sense for some workflows (like changes in `draft` that are relevant for all versions as you mentioned, or comparing versions), we can still set up branches corresponding to the versions, which are copied to the folders in master automatically. But it's probably good to first try a simple setup.
