### ISSUE TITLE
I am having trouble viewing the specs this morning

### ISSUE THREAD

**Issue by gitonthescene** [reconciliation-api/specs#82]
Hello, when trying to view the specs from [the website](https://reconciliation-api.github.io/specs/latest/#service-manifest) this morning it took a long time to download and when it finished it had a read 4 in the upper right corner indicating that there were 4 errors on the page, each a bad reference.

 - skos-reference
 - JSONP
 - beek-2018
 - christen 2012

I don't need anything more from the site at the moment,  I just wanted to report this.

-Regards

**Comment by wetneb** [comment]
Thanks for reporting this. This is a useful reminder that we should publish "final" versions of the specs (for specific versions). As part of that process, respec (the framework we use to write the specs) recommends to take a static snapshot of the specs, so that it can load without any Javascript.

**Comment by wetneb** [comment]
This should now be solved by the hosting of the specs on the w3.org website, as static HTML files:
* for 0.2: https://www.w3.org/community/reports/reconciliation/CG-FINAL-specs-0.2-20230410/
* for 0.1: https://www.w3.org/community/reports/reconciliation/CG-FINAL-specs-0.1-20230321/

The current draft remains a dynamic, respec-based page, but it should not be used by implementers yet:
https://reconciliation-api.github.io/specs/draft/
