### ISSUE TITLE
Normalize naming conventions across the API

### ISSUE THREAD

**Issue by wetneb** [reconciliation-api/specs#95]
In the manifest we have fields such as `identifierSpace` and `feature_view`.
We should settle on a style: either `identifierSpace` and `featureView`, or `identifier_space` and `feature_view`.

I think in JSON it is somehow more common to have `feature_view` than `featureView`.

**Comment by thadguidry** [comment]
Agree, underscore separation

**Comment by wetneb** [comment]
Yeah but on the other side, the `identifierSpace` and `schemaSpace` have been there for ages, whereas `feature_view`, so it would likely be much less disruptive to rename the latter…

**Comment by fsteeg** [comment]
Resolved with #166 (PR for #150, which was a duplicate of this), closing.
